services:
  occtr:
    image: harbor.vcloud.nii.ac.jp/vcp/occtr:26.10.0
    ports:
      - "7947:7947" # serf
    volumes:
      - ./cert:/opt/occ/httpd/cert/:ro
      - ./config:/opt/occ/config:ro
      - ./volume/opt/occ/var:/opt/occ/var
      - ./volume/opt/occ/.ssh:/opt/occ/.ssh
      - ./volume/opt/occ/vc:/opt/occ/vc
    environment:
      - VCP_VCC_PRIVATE_IPMASK=${VCP_VCC_PRIVATE_IPMASK:?VCP_VCC_PRIVATE_IPMASK environment variable is required}
      - VCP_OFFICIAL_REGISTRY_ADDRESS=${VCP_OFFICIAL_REGISTRY_ADDRESS:-harbor.vcloud.nii.ac.jp}
      - CONSUL_BASE_URL=${CONSUL_BASE_URL:-http://127.0.0.1:8500/v1/}
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - VAULT_ADDR=https://localhost:8443
      - VAULT_CACERT=/etc/ssl/certs/ca-certificates.crt
      - VAULT_TOKEN_FILE=/opt/occ/var/vault/root_token.txt
  nginx:
    image: nginx
    ports:
      - "8888:8888"
    volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  jupyter:
    image: harbor.vcloud.nii.ac.jp/vcpjupyter/cloudop-notebook:lab-4.5.7-simple
    user: root
    volumes:
      - ./cert/occtr_ca.crt:/usr/local/share/ca-certificates/occtr_ca.crt:ro
      - ./jupyter-work:/home/jovyan/work
      - jupyter-data:/home/jovyan/.jupyter
    environment:
      - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
      - TZ=JST-9
      - JUPYTER_PORT=8888
      - CHOWN_HOME=yes
      - CHOWN_HOME_OPTS=-R
    # Full config: https://jupyter-server.readthedocs.io/en/latest/users/configuration.html
    command:
      - start-notebook.py
      - --ServerApp.base_url=/jupyter/
volumes:
  jupyter-data: