[project]
site_name = "OCS-VCP-PORTABLE"
docs_dir = "docs"
language = "ja"
repo_url = "https://github.com/nii-gakunin-cloud/ocs-vcp-portable"
repo_name = "ocs-vcp-portable"
nav = [
    { "ocs-vcp-portable" = "README.md" },
    { "クイックスタート" = "quickstart.md" },
    { "プロバイダ情報" = [
        {"mdx" = "providers/mdx.md"},
        {"proxmox" = "providers/proxmox.md"}]
    },
    { "詳細マニュアル" = "manual.md" },
]

features = [
    "content.code.copy",
    "content.code.select",
    "navigation.top",
    "navigation.path"
]
